config/routes.rb
Rails.application.routes.draw do

  get "/", to: "static#index"

  get "/upcoming-concerts", to: "concerts#upcoming"

  get "/sign-up", to: "artists#new"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  post '/logout', to: "sessions#destroy"

  get '/auth/github/callback' => 'sessions#create' 

  get '/auth/facebook/callback' => 'sessions#create' 

  resources :concerts

  resources :artists, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :venues, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  resources :venues, only: [:show] do
    resources :concerts, only: [:show, :index, :new, :edit]
  end

  resources :artists, only: [:show] do
    resources :concerts,  only: [:show, :index, :new, :edit]
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/concert.rb
class Concert < ApplicationRecord

    belongs_to :artist
    belongs_to :venue

    has_one :address, through: :venue

    include ActiveModel::Validations
    validates_with TimeValidator

    validates :start_time, presence: true
    validates :end_time, presence: true
    validates :name, presence: true

    scope :over, -> { where("end_time < ?", DateTime.now) }

    scope :not_over, -> { where("end_time > ?", DateTime.now) }

    scope :upcoming, -> { not_over.where("start_time BETWEEN ? AND ?", DateTime.now, DateTime.now + 30.days,) } 


    def self.search(option, query)
        case option
        when "Name"
            self.where("name LIKE ?", "%#{query}%")
        when "Artist"
            artist = Artist.where("name LIKE ?", "%#{query}%").first
            if artist
                self.where(artist_id: artist.id)
            else
                self.where("name LIKE ?", "%#{query}%")
            end
        when "Venue"
            venue  = Venue.where("name LIKE ?", "%#{query}%").first
            if venue
                self.where(venue_id: venue.id)
            else
                self.where("name LIKE ?", "%#{query}%")
            end
        end
    end



end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

    before_action :require_login
    skip_before_action :require_login, only: [:index, :show, :upcoming]

    def index
        
        if params[:search]
            @concerts = Concert.search(params[:option], params[:search])
        elsif params[:artist_id]
            @artist = Artist.find_by(id: params[:artist_id])
            if @artist
                @concerts = @artist.concerts
            else
                redirect_to concerts_path
            end
        elsif params[:venue_id]
            @venue = Venue.find_by(id: params[:venue_id])
            if @venue
                @concerts = @venue.concerts
            else
                redirect_to concerts_path
            end
        else
            @concerts = Concert.all
        end
    end

    def upcoming
        @concerts = Concert.upcoming
        render "index"
    end

    def show
        if params[:artist_id]
            @artist = Artist.find_by(id: params[:artist_id])
            if @artist.nil?
              redirect_to artists_path, alert: "Artist not found."
            else
                @concert = @artist.concerts.find_by(id: params[:id])
                    redirect_to artist_concerts_path(artist), alert: "Post not found." if @concert.nil?
            end
        elsif params[:venue_id]
            @venue = Venue.find_by(id: params[:venue_id])
            if @venue.nil?
                redirect_to venues_path, alert: "Venue not found."
            else
                @concert = @venue.concerts.find_by(id: params[:id])
                    redirect_to venue_concerts_path(venue), alert: "Concert not found." if @concert.nil?
            end
        else
            @concert = Concert.find(params[:id])
        end
    end

    def new
       
        @concert = Concert.new(artist_id: params[:artist_id], venue_id: params[:venue_id])
    end

    def create
        @concert = Concert.new(concert_params)
        if @concert.save
            redirect_to concert_path(@concert)
        else
            render "new"
        end
    end

    def edit
        if params[:artist_id]
            @artist = Artist.find_by(id: params[:artist_id])
            if @artist.nil?
              redirect_to artists_path, alert: "Artist not found."
            else
                @concert = @artist.concerts.find_by(id: params[:id])
                    redirect_to artist_concerts_path(artist), alert: "Post not found." if @concert.nil?
            end
        elsif params[:venue_id]
            @venue = Venue.find_by(id: params[:venue_id])
            if @venue.nil?
                redirect_to venues_path, alert: "Venue not found."
            else
                @concert = @venue.concerts.find_by(id: params[:id])
                    redirect_to venue_concerts_path(venue), alert: "Concert not found." if @concert.nil?
            end
        else
            @concert = Concert.find(params[:id])
        end
    end

    def update
        @concert = Concert.find_by(id: params[:id])
        if @concert.update(concert_params)
            redirect_to concert_path(@concert)
        else
            render "edit"
        end
    end

    def destroy
        @concert = Concert.find_by(id: params[:id])
        @concert.destroy
        redirect_to concerts_path
    end



    private

    def concert_params
        params.require(:concert).permit(:name, :description, :start_time, :end_time, :artist_id, :venue_id)
    end

end

app/helpers/concerts_helper.rb
module ConcertsHelper

  def artist_id_field(concert)
      if concert.artist.nil?
        select_tag "concert[artist_id]", options_from_collection_for_select(Artist.all, :id, :name)
      else
        hidden_field_tag "concert[artist_id]", concert.artist_id
      end
  end

  def venue_id_field(concert)
      if concert.venue.nil?
        select_tag "concert[venue_id]", options_from_collection_for_select(Venue.all, :id, :name)
      else
        hidden_field_tag "concert[venue_id]", concert.venue_id
      end
  end

  def concert_name_link(concert)
    if @artist
      link_to concert.name, artist_concert_path(@artist, concert)
    elsif @venue
      link_to concert.name, venue_concert_path(@venue, concert) 
    else
      link_to concert.name, concert_path(concert) 
    end
  end

  
  def back_to_artist_or_venue_concerts(concert)
    if @artist
      link_to "Back to Artist", artist_concerts_path(@artist)
    elsif @venue
      link_to "Back to Venue", venue_concerts_path(@venue)
    else
      link_to "Back to Concerts", concerts_path
    end
  end


  def edit_concert_button(concert, artist)
    if artist && artist.concerts.include?(concert)
        button_to "Edit Concert", edit_concert_path(concert)
    end
  end
  
end

app/views/concerts/_concert.html.erb
<div class="concert-container">
    <strong> <%= concert_name_link(concert) %> </strong> <br>
    <%= link_to concert.venue.name, venue_path(concert.venue) %> <br>
    <%= link_to concert.artist.name, artist_path(concert.artist) %> <br>

    Description: <%= concert.description %> <br>
    Start time: <%= concert.start_time.strftime("%B %-d, %Y at %l:%M%P") %> <br>
    End time: <%= concert.end_time.strftime("%B %-d, %Y at %l:%M%P")  %> <br>
</div>
<br>

app/views/concerts/_form.html.erb
<div class="concert-form" >
<%= form_for concert do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :description %>
    <%= f.text_area :description %><br>

    <%= f.label :start_time%>
    <%= f.datetime_field :start_time %><br>

    <%= f.label :end_time%>
    <%= f.datetime_field :end_time %><br>

    <%= artist_id_field(concert)%>
    <%= venue_id_field(concert) %>
  <%= f.submit %>
<% end %> 
</div>

app/views/concerts/edit.html.erb
<h1> New Concert </h1>

<% if @concert.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

<%= form_tag concert_path(@concert) do %>
 <%= render partial: 'form', locals: {concert: @concert} %>
<% end %> 

<br>

<%= back_to_artist_or_venue_concerts(@concert) %>

<%= button_to "Delete Concert", concert_path(@concert), method: :delete %> 

app/views/concerts/index.html.erb
<h1> Concerts </h1>
<%= render @concerts %>

app/views/concerts/new.html.erb
<h1> New Concert </h1>

<% if @concert.errors.any? %>
  <div id="error_explanation">
    <h2>There were some errors:</h2>
    <ul>
      <% @concert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

<%= form_tag concerts_path do %>
 <%= render partial: 'form', locals: {concert: @concert} %>
<% end %> 

If you need to make a new venue, please click here:
<%= link_to "Make a new venue", new_venue_path %>

<br>
<%= back_to_artist_or_venue_concerts(@concert) %>

app/views/concerts/show.html.erb
<h1><%= @concert.name %> </h1> <br>

Artist: <br>
<%= link_to @concert.artist.name, artist_path(@concert.artist)%> <br>

About: <br>
<%= @concert.description %> <br>

Location: <br>

<%= link_to @concert.venue.name, venue_path(@concert.venue)  %> <br>
<%= render partial: "addresses/address", locals: {address: @concert.venue.address ||= Address.all.first} %> <br>

<br>

Start time: <%= @concert.start_time.strftime("%B %-d, %Y at %l:%M%P") %> <br>
End time: <%= @concert.end_time.strftime("%B %-d, %Y at %l:%M%P")  %> <br>

<%= edit_concert_button(@concert, @current_user_artist) %>
<%= back_to_artist_or_venue_concerts(@concert) %>