config/routes.rb
Rails.application.routes.draw do

  get "/", to: "static#index"

  get "/upcoming-concerts", to: "concerts#upcoming"

  get "/sign-up", to: "artists#new"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  post '/logout', to: "sessions#destroy"

  get '/auth/github/callback' => 'sessions#create' 

  get '/auth/facebook/callback' => 'sessions#create' 

  resources :concerts

  resources :artists, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :venues, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  resources :venues, only: [:show] do
    resources :concerts, only: [:show, :index, :new, :edit]
  end

  resources :artists, only: [:show] do
    resources :concerts,  only: [:show, :index, :new, :edit]
  end

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyScene</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= login_logout_button %>
    <%= sign_up_link %>
    
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <div id="concert-search-field">
      <%= form_tag concerts_path, method: :get  do %>
          <label>Search for Concerts:</label>
          <%= select_tag "option", options_for_select(["Name", "Artist", "Venue"])%>
          <%= text_field_tag :search, params[:search]%>
          <%= submit_tag "Search" %>
      <% end %>
    </div>


    <%= yield %>
  </body>
</html>

app/views/layouts/static.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyScene</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>